name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v4
      # - name: Install dependencies
      #   run: npm install
      # - name: Build
      #   run: npm run build
      # - name: Check lint
      #   run: npm run lint
      # - name: Check ENV
      #   run: echo "${{ vars.AWS_SECRET }}"
      - name: Run a script
        env:
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
        run: |
          echo "Using the API key: $AWS_SECRET"
