name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: npm install --package-lock-only
        run: npm ci
      - name: Build project
        run: npm run build --if-present
